/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelectionRouteImport } from './routes/selection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as RequestSlugRouteImport } from './routes/request.$slug'
import { Route as PieceSlugRouteImport } from './routes/piece.$slug'
import { Route as CollectionCategoryRouteImport } from './routes/collection.$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionRoute = SelectionRouteImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSlugRoute = RequestSlugRouteImport.update({
  id: '/request/$slug',
  path: '/request/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PieceSlugRoute = PieceSlugRouteImport.update({
  id: '/piece/$slug',
  path: '/piece/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionCategoryRoute = CollectionCategoryRouteImport.update({
  id: '/collection/$category',
  path: '/collection/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/selection': typeof SelectionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/piece/$slug': typeof PieceSlugRoute
  '/request/$slug': typeof RequestSlugRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/selection': typeof SelectionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/piece/$slug': typeof PieceSlugRoute
  '/request/$slug': typeof RequestSlugRoute
  '/collection': typeof CollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/selection': typeof SelectionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/piece/$slug': typeof PieceSlugRoute
  '/request/$slug': typeof RequestSlugRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/selection'
    | '/sitemap.xml'
    | '/collection/$category'
    | '/piece/$slug'
    | '/request/$slug'
    | '/collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/selection'
    | '/sitemap.xml'
    | '/collection/$category'
    | '/piece/$slug'
    | '/request/$slug'
    | '/collection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/selection'
    | '/sitemap.xml'
    | '/collection/$category'
    | '/piece/$slug'
    | '/request/$slug'
    | '/collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SelectionRoute: typeof SelectionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CollectionCategoryRoute: typeof CollectionCategoryRoute
  PieceSlugRoute: typeof PieceSlugRoute
  RequestSlugRoute: typeof RequestSlugRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection': {
      id: '/selection'
      path: '/selection'
      fullPath: '/selection'
      preLoaderRoute: typeof SelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$slug': {
      id: '/request/$slug'
      path: '/request/$slug'
      fullPath: '/request/$slug'
      preLoaderRoute: typeof RequestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piece/$slug': {
      id: '/piece/$slug'
      path: '/piece/$slug'
      fullPath: '/piece/$slug'
      preLoaderRoute: typeof PieceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$category': {
      id: '/collection/$category'
      path: '/collection/$category'
      fullPath: '/collection/$category'
      preLoaderRoute: typeof CollectionCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SelectionRoute: SelectionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CollectionCategoryRoute: CollectionCategoryRoute,
  PieceSlugRoute: PieceSlugRoute,
  RequestSlugRoute: RequestSlugRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
